### ISSUE TITLE
Ask you a question about Watchface

### ISSUE THREAD

**Issue by MCChao211** [banjun/WatchFaceDumper#4]
In your watchface file, I see a lot of property definitions. What exactly do the definitions of these properties mean? I didn't find any relevant documentation from Apple developer website, where have you seen how to define watchface files?

**Comment by banjun** [comment]
There is no official information from Apple. That is the reason I analyze the format and then I published as WatchFaceDumper, an OSS project. Moreover, watchfaces have different data structures although they share a common structures roughly. Photos, kaleidoscope, whistler-analog and Portrait (#3) are the only face types I already analyzed. Other face types needs to be analyzed.
